issues:
  max-same-issues: 0
  exclude-rules:
    - linters:
        - gosec
      text: G115
    - linters:
        - revive
      text: var-naming
    - linters:
        - revive
      text: exported
    - linters:
        - revive
      text: empty-block
    - linters:
        - revive
      text: unused-parameter
linters:
  enable:
    - asciicheck
    - contextcheck
    - durationcheck
    - errorlint
    - gci
    - gofmt
    - gofumpt
    - goimports
    - gomodguard
    - gosec
    - gosimple
    - importas
    - misspell
    - nakedret
    - nolintlint
    - predeclared
    - revive
    - typecheck
    - unparam
  disable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/shirou)
  gomodguard:
    blocked:
      modules:
        - io/ioutil:
            recommandations:
              - io
              - os
