issues:
  max-same-issues: 0
  exclude-rules: 
  - linters: 
    - gosec
    text:  "G204"
  - linters: 
    - revive
    text:  "var-naming"
  - linters: 
    - revive
    text:  "exported"
linters:
  enable:
    - asciicheck
    - durationcheck
    - errorlint
    - gci
    - gochecknoinits
    - gofmt
    - gofumpt
    - gosec
    - gosimple
    - megacheck
    - misspell
    - nakedret
    - nolintlint
    - predeclared
    - revive
    - typecheck
    - unparam
  disable:
    - deadcode
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - unused
    - varcheck
