//go:build freebsd && riscv64
// +build freebsd,riscv64

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs host/types_freebsd.go

package host

const (
	sizeofPtr      = 0x8
	sizeofShort    = 0x2
	sizeofInt      = 0x4
	sizeofLong     = 0x8
	sizeofLongLong = 0x8
	sizeOfUtmpx    = 0xc5
)

type (
	_C_short     int16
	_C_int       int32
	_C_long      int64
	_C_long_long int64
)

type (
	Utmp  _cgopackage.Incomplete
	Utmpx struct {
		Type      uint8
		Pad_cgo_0 [8]byte
		Id        [8]uint8
		Pad_cgo_1 [4]byte
		User      [32]uint8
		Line      [16]uint8
		Host      [128]uint8
	}
)
