// SPDX-License-Identifier: BSD-3-Clause
// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_aix.go | sed 's/\*byte/uint64/'

package process

type prTimestruc64 struct {
	Sec    int64
	Nsec   int32
	X__pad uint32
}
type lwpSinfo struct {
	Lwpid   uint64
	Addr    uint64
	Wchan   uint64
	Flag    uint32
	Wtype   uint8
	State   uint8
	Sname   uint8
	Nice    uint8
	Pri     int32
	Policy  uint32
	Clname  [8]uint8
	Onpro   int32
	Bindpro int32
	Ptid    uint32
	X_pad1  uint32
	X_pad   [7]uint64
}
type psinfo struct {
	Flag   uint32
	Flag2  uint32
	Nlwp   uint32
	X_pad1 uint32
	Uid    uint64
	Euid   uint64
	Gid    uint64
	Egid   uint64
	Pid    uint64
	Ppid   uint64
	Pgid   uint64
	Sid    uint64
	Ttydev uint64
	Addr   uint64
	Size   uint64
	Rssize uint64
	Start  prTimestruc64
	Time   prTimestruc64
	Cid    uint16
	X_pad2 uint16
	Argc   uint32
	Argv   uint64
	Envp   uint64
	Fname  [16]uint8
	Psargs [80]uint8
	X_pad  [8]uint64
	Lwp    lwpSinfo
}
